/**
 * Output produced by the Risk Auditor Agent.
 */
export interface RiskAuditResult {

    riskSummary: string;

    vulnerabilities: string[];

    warnings: string[];

    riskLevel:
        | "LOW"
        | "MEDIUM"
        | "HIGH";
}

/**
 * Output produced by the Macro Analyst Agent.
 */
export interface MacroResult {

    macroView: string;

    tacticalTilts: string[];

    opportunities: string[];
}

/**
 * Output produced by the Tax Optimizer Agent.
 */
export interface TaxResult {

    observations: string[];

    recommendations: string[];
}

/**
 * Output produced by the Portfolio Advisor Agent.
 *
 * Focus:
 * - diversification
 * - portfolio quality
 * - improvement suggestions
 */
export interface PortfolioAdvisorResult {

    summary: string;

    diversificationInsights: string[];

    recommendations: string[];
}

/**
 * Final response returned to the frontend.
 *
 * Generated by the Synthesizer Agent.
 */
export interface AdvisoryResponse {

    summary: string;

    riskAnalysis: string;

    diversificationAnalysis: string;

    macroInsights: string;

    taxInsights: string;

    recommendations: string[];

    warnings: string[];
}